baseURL = "https://www.mathewinkson.com/"
languageCode = "en-AU"
title = "Mathew Inkson"
disableKinds = ["section"]
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-5W1PKV4DSY"

[frontmatter]
  lastmod = ["lastmod"]

[taxonomies]
  category = "categories"

[params]  
  categories = ["Music","Technology","Sport","Television", "Government", "Misc"]
  canonURL = "https://www.mathewinkson.com"
  author = "Mathew Inkson"
  ogimage = "og.png"
  sitename = "Mathew Inkson"
  twitter = "@imathew"
  facebook = "https://facebook.com/imathew"
  github = "https://github.com/imathew"
  staticman = true

[permalinks]
  posts = '/:year/:month/:slug/'
  pages = ":slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true