baseURL = ""
#baseURL = "//www.mathewinkson.com/"
languageCode = "en-AU"
title = "Mathew Inkson"
disableKinds = ["section"]
enableEmoji = true
enableRobotsTXT = true
#googleAnalytics = "UA-31343840-1"
#enableGitInfo = true
#canonifyURLs = true

[frontmatter]
  lastmod = ["lastmod"]

[taxonomies]
  category = "categories"

[params]  
  categories = ["Music","Technology","Sport","Television", "Government", "Misc"]
  canonURL = "//www.mathewinkson.com"
  author = "Mathew Inkson"
  ogimage = "og.png"
  sitename = "Mathew Inkson"
  twitter = "@imathew"
  facebook = "//facebook.com/imathew"
  github = "//github.com/imathew"
  staticman = true

[permalinks]
  posts = '/:year/:month/:slug/'
  pages = ":slug"
