baseURL = "https://www.mathewinkson.com/"
#baseURL = "https://thankful-smoke-0bcb23d1e.2.azurestaticapps.net/"
#baseURL = ""
languageCode = "en-AU"
title = "Mathew Inkson"
disableKinds = ["section"]
enableEmoji = true
enableRobotsTXT = true
#googleAnalytics = "UA-31343840-1"

[frontmatter]
  lastmod = ["lastmod"]

[taxonomies]
  category = "categories"

[params]  
  categories = ["Music","Technology","Sport","Television", "Government", "Misc"]
  canonURL = "https://www.mathewinkson.com"
  author = "Mathew Inkson"
  ogimage = "og.png"
  sitename = "Mathew Inkson"
  twitter = "@imathew"
  facebook = "https://facebook.com/imathew"
  github = "https://github.com/imathew"
  staticman = true

[permalinks]
  posts = '/:year/:month/:slug/'
  pages = ":slug"
